# Generated by Django 6.0.4 on 2026-04-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conferences", "0001_initial"),
        ("researchers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("abstract", models.TextField()),
                ("keywords", models.CharField(blank=True, max_length=250)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("corresponding_email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "paper_pdf",
                    models.FileField(blank=True, null=True, upload_to="papers/pdfs/"),
                ),
                (
                    "paper_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="papers/images/"
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        blank=True, related_name="papers", to="researchers.researcher"
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="papers",
                        to="conferences.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_date", "title"],
            },
        ),
    ]
