# Generated by Django 6.0.4 on 2026-04-30 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Researcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "academic_rank",
                    models.CharField(
                        choices=[
                            ("assistant", "Assistant Professor"),
                            ("associate", "Associate Professor"),
                            ("professor", "Professor"),
                            ("lecturer", "Lecturer"),
                            ("student", "Graduate Student"),
                        ],
                        default="student",
                        max_length=30,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="researchers/images/"
                    ),
                ),
                (
                    "cv_document",
                    models.FileField(
                        blank=True, null=True, upload_to="researchers/cvs/"
                    ),
                ),
                ("biography", models.TextField(blank=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researchers",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
