# Generated by Django 6.0.4 on 2026-04-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("researchers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "conference_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="conferences/images/"
                    ),
                ),
                (
                    "proceedings_document",
                    models.FileField(
                        blank=True, null=True, upload_to="conferences/documents/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attended_conferences",
                        to="researchers.researcher",
                    ),
                ),
                (
                    "organizers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="organized_conferences",
                        to="researchers.researcher",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
