# Generated by Django 6.0.4 on 2026-04-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("founded_date", models.DateField(blank=True, null=True)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "department_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="departments/images/"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
